packages:
  - 'apps/*'
  - 'packages/*'
  - 'extension'
allowBuilds:
  esbuild: true
overrides:
  undici: '>=7.29.0'
  js-yaml: '>=5.2.3'
  fast-uri: '>=3.1.5'
  brace-expansion: '>=1.1.18'
  image-size: '>=2.0.2'
